apiVersion: v1
kind: Service
metadata:
  labels:
    app: slurmd
  name: slurmd-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 6818
  selector:
    app: slurmd
  type: ClusterIP
