apiVersion: v1
kind: Service
metadata:
  labels:
    app: slurm-master
  name: slurmctld
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 6817
  selector:
    app: slurm-master
  type: ClusterIP