version: '2'

services:
  slurmctld:
    environment:
      SLURM_CLUSTER_NAME: ddhpc
      SLURM_CONTROL_MACHINE: slurmctld
      SLURM_NODE_NAMES: slurmd
    tty: true
    hostname: slurmctld
    image: datadrivenhpc/slurmctld:latest
    links:
    - slurmd:SLURM_NODES
    stdin_open: true
  slurmd:
    environment:
      SLURM_CONTROL_MACHINE: slurmctld
      SLURM_CLUSTER_NAME: ddhpc
      SLURM_NODE_NAMES: slurmd
    tty: true
    hostname: slurmd
    image: datadrivenhpc/slurmd
    stdin_open: true
